  
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuild:hello-world .   
      - docker run -p 8080:8080 -d codebuild
  post_build:
    commands:
      - echo Build completed on `date`
